fix: checks for extension installation
WhoTargetsMe/project-berlin-lab pull request #12
Opened 2023-05-19 14:58 UTC by michellejanay

2023-05-19 19:34 UTC, skinofstars requested changes

2023-05-19 19:34 UTC, skinofstars commented on src/routes/landing/+page.ts
> +			goto('../installation');
This shouldn't be in here. If you want to use a promise, then the `goto` should be in the catch (either as `.catch((err) => { ... })` or in an await `try .. catch` block). The way you're doing it here means the promise is resolving after you've already navigated away.

2023-05-19 21:31 UTC, michellejanay commented on src/routes/landing/+page.ts
> +			goto('../installation');
I fixed it(:

2023-05-20 08:50 UTC, skinofstars commented on src/routes/landing/+page.svelte
Did you want to delete this page?

2023-05-20 08:50 UTC, skinofstars commented on src/routes/+page.ts
> +		installed: is_installed
If this is returning a boolean, it really should be `isInstalled`. 

The other items here are values, so we should use the camelCase for them. The exceptions are typically as follows:

1. A consant value, like PUBLIC_EXTENSION_ID, or if you need to set an external one, like MAX_COLLECTION_AMOUNT = 50, so you don't have random numbers lying around.
2. A direct mapping to a database column. TAble columns should always be underscores. This often means where you query a table, the values come back as underscores. Same if you're going to write to that table (See KnexJS). This can make it clear that you're dealing with databases columns.

2023-05-20 10:37 UTC, michellejanay commented on src/routes/landing/+page.svelte
Ah, yes. I moved it to be the main route/landing page. Should I move it back?

2023-05-20 15:31 UTC, skinofstars commented on src/routes/+page.svelte
> +		title="Click below to continue the study"
should be in language files right?

2023-05-20 15:31 UTC, skinofstars commented on src/routes/+page.svelte
> +		title="Click below to continue the study"
So we have the question on where the redirect is... let's not worry about langauge file per se, but we dow want to consider what we want to do with this design in the context fo Sam said

2023-05-20 15:31 UTC, skinofstars commented on src/routes/landing/+page.svelte
oh , so we don't have a `/landing` route? that's fine if you think that's redundant

2023-05-20 15:45 UTC, michellejanay commented on src/routes/+page.svelte
> +		title="Click below to continue the study"
As in converted to i18? I will look into this! 

The redirect to install is in +page.ts, should this redirect be changed as well to go to a component similar to the install? 

Is it safe to assume that participants will not be able to access the lab without prolific parameters? Maybe we can just have an error page if they don't have those params or the extension, and an introduction to the study, what they can expect, ect, with the start button, before starting?

2023-05-20 16:45 UTC, skinofstars commented
I’m not sure that’s100% safe to assume. We can expect people who land there to have the params, and we’re just doing a check. If they aren’t, then there is probably a homepage that talks any the study in general terms to a variety of audiences. Participants, fellow researchers, journalists, all sorts. So, on /, then they’re people. But on /experiment or /landing or whatever, then they’re participants. On 20 May 2023, at 16:45, Michelle Janay ***@***.***> wrote:﻿
@michellejanay commented on this pull request.



In src/routes/+page.svelte:
> -	</div>
-</div>
+{#if !hasProlificParams}
+	<main class="container h-full mx-auto flex justify-center items-center">
+		<section class="card p-6 bg-white shadow-lg">
+			<h3 class="m-4">
+				{$LL.prolific()}
+			</h3>
+			<a type="button" class="btn variant-filled mt-4 float-right" href={PUBLIC_PROLIFIC_LINK}>
+				{$LL.prolific_button()}
+			</a>
+		</section>
+	</main>
+{:else}
+	<CardWithButton
+		title="Click below to continue the study"

As in converted to i18? I will look into this!
The redirect to install is in +page.ts, should this redirect be changed as well to go to a component similar to the install?
Is it safe to assume that participants will not be able to access the lab without prolific parameters? Maybe we can just have an error page if they don't have those params or the extension, and an introduction to the study, what they can expect, ect, with the start button, before starting?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2023-05-20 17:00 UTC, michellejanay commented
Ah okay, so it would be better if the route was put back, so the landing
page could be that page that talks about the study to general audiences, so
participants will just be linked to the correct page. I will put it back to
how it was!

So will the typeform tell participants what will happen/what to expect in
the experiment part of the study, or should the 'click the link to start
the study' page do that? Or should we put a redirect directly to Facebook
if they have the extension installed, instead of having that page?

On Sat, 20 May 2023, 17:45 Kevin Carmody, ***@***.***> wrote:

> I’m not sure that’s100% safe to assume. We can expect people who land
> there to have the params, and we’re just doing a check. If they aren’t,
> then there is probably a homepage that talks any the study in general terms
> to a variety of audiences. Participants, fellow researchers, journalists,
> all sorts. So, on /, then they’re people. But on /experiment or /landing or
> whatever, then they’re participants. On 20 May 2023, at 16:45, Michelle
> Janay ***@***.***> wrote:﻿
> @michellejanay commented on this pull request.
>
>
>
> In src/routes/+page.svelte:
> > - </div>
> -</div>
> +{#if !hasProlificParams}
> + <main class="container h-full mx-auto flex justify-center items-center">
> + <section class="card p-6 bg-white shadow-lg">
> + <h3 class="m-4">
> + {$LL.prolific()}
> + </h3>
> + <a type="button" class="btn variant-filled mt-4 float-right"
> href={PUBLIC_PROLIFIC_LINK}>
> + {$LL.prolific_button()}
> + </a>
> + </section>
> + </main>
> +{:else}
> + <CardWithButton
> + title="Click below to continue the study"
>
> As in converted to i18? I will look into this!
> The redirect to install is in +page.ts, should this redirect be changed as
> well to go to a component similar to the install?
> Is it safe to assume that participants will not be able to access the lab
> without prolific parameters? Maybe we can just have an error page if they
> don't have those params or the extension, and an introduction to the study,
> what they can expect, ect, with the start button, before starting?
>
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are
> receiving this because your review was requested.Message ID: ***@***.***>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WhoTargetsMe/project-berlin-lab/pull/12#issuecomment-1555949882>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATFLUQT3A3Z4AM36Z56NRZ3XHDYKPANCNFSM6AAAAAAYH4P5LU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-22 08:39 UTC, skinofstars requested changes
There's a very confusing bit of code in this. Could you please either rewrite to make it readable, or add a comment. Ta

2023-05-22 08:39 UTC, skinofstars commented on src/routes/landing/+page.ts
> +	!chrome.runtime && goto('../installation');
wait, wat?

2023-05-22 10:07 UTC, skinofstars approved these changes

2023-05-22 13:41 UTC, merged