feat: flags reduced to object from array
WhoTargetsMe/project-berlin-lab pull request #18
Opened 2023-05-23 11:52 UTC by michellejanay

2023-05-23 19:27 UTC, skinofstars requested changes

2023-05-23 19:27 UTC, skinofstars commented on src/lib/flags-store.ts
- I like the reduce as it's a more functional approach. 
- Using the `posthog.feature_flags.getFlags()` removes a level of nesting.
- We want our vars to describe what they contain, not the type of structure they are, i.e. `flagsWithPayload`, not `flagsObj`
- Again, removing the `!` boolean inversions make it easier to read
- We can add some typing too while we're at it

Something like this is a combination of the two approaches

```ts
const posthogFlags: [string] = posthog.feature_flags.getFlags();

const flagsWithPayload: { [key: string]: { enabled: boolean; payload: any } } =
  posthogFlags.reduce((result, item) => {
    return {
      ...result,
      [item]: {
        enabled: posthog.getFeatureFlag(item),
        payload: posthog.getFeatureFlagPayload(item),
      },
    };
  }, {});

flags.set(flagsWithPayload)
```

2023-05-23 22:23 UTC, michellejanay commented on src/lib/flags-store.ts
This is a great solution! 
I didn't think to declare the object in the parameters, but that's really cool 😍
Also, I was wondering how to define functions in TypeScript! I saw fn: but it wasn't working for me 🤔 I appreciate this! 
Ah, yes, the naming was on the spur of the moment, my bad 😅
Can we write all of our functions and variables like this?

2023-05-24 07:52 UTC, skinofstars approved these changes

2023-05-25 06:46 UTC, merged