feat(PB-69): shuffle and sort by post type feature flags added
WhoTargetsMe/project-berlin-lab pull request #30
Opened 2023-06-08 09:11 UTC by michellejanay

# (PB-69): Feed order flags

- shuffle, sort by post type, and show/hide labels feature flags added

## Related Ticket/PR

- [Jira ticket](https://whotargetsme.atlassian.net/browse/PB-69)

---

## Changes

Adds more feature flags on the page, to include:

random vs Facebook sorting
With vs without social metrics
Engagement based vs random vs something smart (content based) sorting

The engagement based could also be a third condition in experiment
with vs without labels

---

## Concerns

Concerns with flags sometimes not loading prior to project-berlin-extension page loading.
Things tried:
-setting the flags-store to be asynchronous
-wrapping the flags-store in a function and calling it in different +page and +layout files
-wrapping the switch statement in an onFeatureFlags - this solution doesn't work for components
-wrapping switch/flags in an if block to check that the Object is not empty - this solution will keep the page from breaking, but it will also make it so that reactions, time posted, and labels will not show if $flags obj is empty

---

## Things to consider 

In order to solve the problem of the flags sometimes loading after the page loads, we could consider server-side initialization and Posthog bootstrapping

---

## Requirements Before Merging

none

2023-06-08 09:27 UTC, skinofstars requested changes
Is there a way in Posthog to limit these to only be able to select one?

2023-06-08 09:27 UTC, skinofstars commented on src/routes/project-berlin-experiment/+page.svelte
> +	if ($flags.should_emphasize_organic_posts.enabled) {
thsi should be a switch!

2023-06-08 09:43 UTC, michellejanay commented
> Is there a way in Posthog to limit these to only be able to select one?

As in only have one at a time enabled? We can set the conditions to match the studyID and also specify the percentage of people it gets rolled out to

Also I will update the PR Template and make it a switch statement!

2023-06-08 13:05 UTC, skinofstars approved these changes

2023-06-08 13:06 UTC, skinofstars commented on src/routes/project-berlin-experiment/+page.svelte
> +		case $flags.should_not_show_sponsored.enabled:
you could remove sponsored and priolritise engagement

2023-06-08 13:12 UTC, skinofstars commented on src/routes/project-berlin-experiment/+page.svelte
> +			sortPosts('ORGANIC');
let posts = data.posts.posts;

// order block
posts = sortBy(posts, 'ORGANIC')

// hide block
posts = removeBy(posts, 'SPONSORED')

2023-06-13 13:31 UTC, skinofstars approved these changes
console to remove, but that's it really

2023-06-13 13:31 UTC, skinofstars commented on src/routes/project-berlin-experiment/+page.svelte
> +				console.log('emphasize sponsored');
remove console

2023-06-15 16:02 UTC, closed without merging